#!/bin/bash -x

DOCKER_TAG="docker_$DOCKER_VERSION-buildx_$BUILDX_VERSION"
IMAGE_NAME="ghcr.io/maniator/dind-buildx:$DOCKER_TAG"
DOCKERFILE_PATH="$PWD/Dockerfile"

export IMAGE_NAME DOCKERFILE_PATH
# shellcheck disable=SC1091
. "$PWD/hooks/build"
