#!/bin/bash -x
REPO="ghcr.io/$GITHUB_REPO"
IMAGE_NAME="$REPO:docker_$DOCKER_VERSION-buildx_$BUILDX_VERSION"
LABELED_IMAGE="$REPO:$DOCKER_LABEL"
TAR_LOCATION="./.docker/docker-with-buildx.tar"

mkdir -p ./.docker
docker save "$IMAGE_NAME" -o "$TAR_LOCATION"

if gh release create -n "" -t "" "v$DOCKER_VERSION-$BUILDX_VERSION";
then
    gh release upload "v$DOCKER_VERSION-$BUILDX_VERSION" "$TAR_LOCATION#Docker Image"
fi

docker tag "$IMAGE_NAME" "$LABELED_IMAGE"
docker push --all-tags "$REPO"

exit 0
