#!/bin/bash -ex

TARGET_ARCH=$(echo "$1" | sed 's/linux//g' | sed 's/\///g')

case "$TARGET_ARCH" in
    *amd64)
        QEMU_ARCH="x86_64"
        ;;
    *arm32v5)
        QEMU_ARCH="arm"
        ;;
    *arm32v6)
        QEMU_ARCH="arm"
        ;;
    *arm32v7)
        QEMU_ARCH="arm"
        ;;
    *armv6)
        QEMU_ARCH="arm"
        ;;
    *armv7)
        QEMU_ARCH="arm"
        ;;
    *arm64v8)
        QEMU_ARCH="aarch64"
        ;;
    *i386)
        QEMU_ARCH="i386"
        ;;
    *)
        echo "[---] Unknown target architecture, skipping qemu-user-static download"
        exit 0
        ;;
esac

if [[ ! -f qemu-${QEMU_ARCH}-static ]]; then
    echo "[***] Downloading ${QEMU_DOWNLOAD_URL}/${QEMU_LATEST_TAG}/x86_64_qemu-${QEMU_ARCH}-static.tar.gz"
    curl -sL "${QEMU_DOWNLOAD_URL}/${QEMU_LATEST_TAG}/x86_64_qemu-${QEMU_ARCH}-static.tar.gz" \
        | tar xzv
else
    echo "[***] qemu-${QEMU_ARCH}-static already exists. Skipping download."
fi
