#!/bin/bash -x

if gh release create -n "" -t "" "v$DOCKER_VERSION-$BUILDX_VERSION";
then
    mkdir -p ./.docker
    TAR_LOCATION="./.docker/docker-with-buildx.tar.gz"

    docker pull "$IMAGE_NAME"
    docker save "$IMAGE_NAME" | gzip > "$TAR_LOCATION"

    gh release upload "v$DOCKER_VERSION-$BUILDX_VERSION" "$TAR_LOCATION#Docker Image"
fi

exit 0
