#!/bin/bash -ex

WORKDIR=$PWD
IMAGE_NAME=${IMAGE_NAME:-maniator/docker-with-buildx}
DOCKERFILE_PATH=${DOCKERFILE_PATH:-$WORKDIR/Dockerfile}
DOCKER_TAG=${DOCKER_TAG:-latest}
DOCKER_CONFIG=${DOCKER_CONFIG:-$WORKDIR/.docker}
BUILDX_DIR=$DOCKER_CONFIG/buildx

run_build () {
    DOCKER_BUILDKIT=1 \
    docker build -f "$DOCKERFILE_PATH" \
        -t "$IMAGE_NAME" --target=buildx_image \
        --progress=plain . "$@"
}

# "this" implies a pull request test build
if [ "$DOCKER_TAG" = latest ] || [ "$DOCKER_TAG" = this ]; then
    run_build --build-arg DOCKER_VERSION=latest --build-arg BUILDX_VERSION=latest
else
    grep_tags=$(echo "$DOCKER_TAG" | grep -Eo '(docker_|buildx_)?(([0-9]+\.){2}[0-9]+)')
    build_tags=$(echo "$grep_tags" | xargs -I '{}' -t sh -c "./hooks/build_tags '{}'" | tr -s '\n' ' ')

    export -f run_build 
    export BUILDX_DIR WORKDIR IMAGE_NAME DOCKERFILE_PATH
    echo "$build_tags" | xargs -I '{}' -t bash -c "run_build {}"
fi
