#!/bin/sh -ex

WORKDIR=$PWD
IMAGE_NAME=${IMAGE_NAME:-maniator/docker-with-buildx}
DOCKERFILE_PATH=${DOCKERFILE_PATH:-$WORKDIR/Dockerfile}
DOCKER_TAG=${DOCKER_TAG:-latest}
DOCKER_CONFIG=${DOCKER_CONFIG:-$WORKDIR/.docker}
BUILDX_DIR=$DOCKER_CONFIG/buildx

run_docker () {
    mkdir -p "$BUILDX_DIR"
    docker run --rm \
        -e DOCKER_TLS_CERTDIR=/certs \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v "$BUILDX_DIR":/env_configs/.docker/buildx \
        -v "$WORKDIR":"$WORKDIR" -w "$WORKDIR" maniator/docker-with-buildx "$@"
}

run_build () {
    run_docker build -f "$DOCKERFILE_PATH" \
        -t "$IMAGE_NAME" --target=buildx_image \
        --load . "$@"
}

create_builder () {
    run_docker create --driver docker-container --use
}

create_builder

# "this" implies a pull request test build
if [ "$DOCKER_TAG" = latest ] || [ "$DOCKER_TAG" = this ]; then
    run_build
else
    BUILDX_VERSION=$(echo "$DOCKER_TAG" | cut -d '-' -f 2)
    DOCKER_VERSION=$(echo "$DOCKER_TAG" | cut -d '-' -f 1)

    run_build \
        --build-arg BUILDX_VERSION="$BUILDX_VERSION" \
        --build-arg DOCKER_VERSION="$DOCKER_VERSION"
fi
