#!/bin/bash -ex
# hooks/post_checkout
# - https://docs.docker.com/docker-cloud/builds/advanced/
# - https://stackoverflow.com/questions/54578066/how-to-build-a-docker-image-on-a-specific-architecture-with-docker-hub.
## Set QEMU URL and TAG, no time wasted if we are not building multiple architectures
QEMU_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
QEMU_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
    | grep 'name.*v[0-9]' \
    | head -n 1 \
    | cut -d '"' -f 4)

## Unshallow the repository to get all the tags.
if [ -f "$(git rev-parse --git-dir)/shallow" ]; then
    echo "[***] Unshallowing to get correct tags to work."
    git fetch --tags --unshallow --quiet origin
else
    echo "[***] Not a shallow repository."
fi

export QEMU_DOWNLOAD_URL QEMU_LATEST_TAG
docker buildx bake --print -f docker-bake.hcl \
    | jq -r ".target.build.platforms" \
    | grep -Eo 'linux/([a-z0-9/]+)' \
    | xargs -t -I '{}' sh -c ". $(pwd)/hooks/scripts/install_qemu {}"
