#!/bin/bash -x

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --use --driver docker-container

docker buildx ls
docker buildx inspect --bootstrap

# remove old image
docker image rm "$IMAGE_NAME"
