#!/bin/bash

# Register qemu-*-static for all supported processors except the 
# current one, but also remove all registered binfmt_misc before
docker run --rm --privileged multiarch/qemu-user-static:register --reset

docker run --privileged --rm tonistiigi/binfmt --install all

# Create builder container
docker buildx create --use --driver docker-container

echo "Build information"
docker buildx inspect --bootstrap
