#!/bin/bash -ex

docker run --privileged --rm tonistiigi/binfmt --install all

# Create builder container
docker buildx create --use --driver docker-container

docker buildx ls
docker buildx inspect --bootstrap
